#
# Python modules below are needed to run example notebook scripts
#
name: pyrte_dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11,<3.13
  - pytest
  - rte_rrtmgp
  - dask
  - pandas<=2.3.0
  - typing_extensions
  - pre-commit
  - cmake
  - ninja
  - pip
  - pip:
    - -e ..
